spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://111.231.104.76:3306/shop
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select * from product_info
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8060
