env: dev
spring:
  application:
    name: PRODUCT
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.231.104.76:3306/shop
    username: root
    password: lyy123456
server:
  port: 8001
